name: admin
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.5
  open_file: ^3.2.1
  excel: 2.0.0-null-safety-3
  readmore: ^2.1.0
  very_good_analysis: ^2.4.0
  cupertino_icons: ^1.0.2
  flow_builder: ^0.0.5
  http: ^0.13.4
  cloud_firestore: ^2.5.3
  firebase_core: ^1.7.0
  mailer: ^5.0.2
  google_fonts: ^2.1.0
  flutter_bloc: ^7.3.0
  equatable: ^2.0.3
  font_awesome_flutter: ^9.2.0
  firebase_auth: ^3.1.3
  authentication_repository:
    path: ../packages/authentication_repository
  cache:
    path: ../packages/cache
  form_inputs:
    path: ../packages/form_inputs
  formz: ^0.4.1
  feedo_repository:
    path: ../packages/feedo_repository
  feedo_ui:
    path: ../packages/feedo_ui
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
  